# Generated by Django 3.0.5 on 2020-05-18 10:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200518_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='references',
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
