# Generated by Django 3.0.5 on 2020-05-18 10:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
